version: '3'

services:
  web:
    build: docker/apache
    volumes:
      - ./src:/var/www/html/
      - /var/www/html/.git/
    network_mode: "bridge"
    restart: always
    ports:
      - "80:80"
#    environment:
#      - VIRTUAL_HOST
#      - VIRTUAL_PROTO
#      - VIRTUAL_PORT
#    expose:
#      - 443
    links:
      - db
  db:
    build: docker/mysql
    ports:
      - 3309:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d
    network_mode: "bridge"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
