version: '3'
services:
  web:
    build: docker\apache\
    volumes:
      - "./src:/var/www/html"
      - "/var/www/html/.git"
      - ./docker/apache/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-local.ini
    # environment:
    #   VIRTUAL_HOST: contao.local,en.contao.local
    ports:
    - 80:80
    network_mode: "bridge"
    links:
      - mailhog
      - db
  db:
    build: docker\mysql\
    environment:
      MYSQL_DATABASE: contao
      MYSQL_ROOT_PASSWORD: contao
      MYSQL_USER: contao
      MYSQL_PASSWORD: contao
    volumes:
      - "./data:/var/lib/mysql"
      - "./docker/mysql/dumps:/docker-entrypoint-initdb.d"
      - "./docker/mysql/dump-export:/home/dumps"
      - "./docker/mysql/scripts:/home/scripts"
    ports:
      - "3308:3306"
    network_mode: "bridge"
  mailhog:
    build: docker/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    environment:
    - VIRTUAL_HOST=mailhog.local
    - VIRTUAL_PORT=8025
    network_mode: "bridge"
